<a href="https://colab.research.google.com/github/Gofanz17/porto_project/blob/main/scrapping/WebScrapping_DOTA_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# DOTA 2 Heroes Attributes

![dota2](https://cdns.klimg.com/bola.net/library/upload/21/2018/09/hero-dota-2_61002e6.jpg)

Goals of this project is to scrape the atribut of DOTA2 Heroes dataset into CSV file from [DOTA 2 Fandom Website](https://dota2.fandom.com/wiki/Table_of_hero_attributes). 
The Scrapping using BeautifulSoup from python library.

##**WEBSCRAPPING**

In [1]:
#import libraries

import pandas as pd
import numpy as np
from urllib.request import urlopen
from bs4 import BeautifulSoup
import warnings
import os
warnings.filterwarnings('ignore')

In [2]:
#write the url into variable
url = 'https://dota2.fandom.com/wiki/Table_of_hero_attributes'
#open the url 
html = urlopen(url)

In [3]:
soup = BeautifulSoup(html, 'lxml')
type(soup)

bs4.BeautifulSoup

In [4]:
#Get the table of contents
rows = soup.find_all('tr')

all_rows = []
for row in rows:
  row_td = row.find_all('td')
  row_td = str(row_td)
  row_td = BeautifulSoup(row_td, 'lxml').get_text()
  row_td = row_td.replace('\r', '')
  row_td = row_td.replace('\n', '')
  row_td = row_td.replace(' ','')

  all_rows.append(row_td)

print(all_rows)

['[]', '[Abaddon,,22,2.8,103.2,23,1.5,66.5,18,2,76,63,6.3,245.7,325,2.83,50,60,150,120,1.7,0.56,0.41,1800,800,0.6,24,3.2,2]', '[Alchemist,,25,2.9,109.1,22,1.5,65.5,25,1.8,77.2,72,6.2,251.8,305,2.67,52,58,150,100,1.7,0.35,0.65,1800,800,0.6,24,2.75,2]', '[AncientApparition,,20,1.9,75.1,20,2.2,83.8,23,3.4,121.6,63,7.5,280.5,285,2.33,44,54,675,100,1.7,0.45,0.3,1800,800,0.6,24,2.25,0]', '[Anti-Mage,,23,1.6,69.4,24,2.8,105.2,12,1.8,64.2,59,6.2,238.8,310,4,53,57,150,100,1.4,0.3,0.6,1800,800,0.6,24,2.55,2]', '[ArcWarden,,22,2.6,97.4,20,2.5,92.5,24,2.6,99.4,66,7.7,289.3,285,2.33,47,57,625,100,1.7,0.3,0.7,1800,800,0.7,24,2.45,2]', '[Axe,,25,3.4,123.6,20,2.2,83.8,18,1.6,64.4,63,7.2,271.8,310,2.33,52,56,150,100,1.7,0.4,0.5,1800,800,0.6,24,5.25,2]', '[Bane,,22,2.5,94.5,22,2.5,94.5,22,2.5,94.5,66,7.5,283.5,305,4.67,55,61,400,100,1.7,0.3,0.7,1800,1200,0.6,24,2.45,4]', '[Batrider,,28,2.9,112.1,15,1.8,67.2,22,2.9,106.1,65,7.6,285.4,300,3.5,39,43,400,100,1.7,0.3,0.54,1600,800,0.9,24,4.55,2]', '[Beastmaster,,23,2.9,107.1,18,1.6,64.4,16,1.9,71.1,57,6.4,242.6,305,3,56,60,150,100,1.7,0.3,0.7,1800,800,0.6,24,2.55,2]', '[Bloodseeker,,24,2.7,102.3,22,3.1,111.9,17,2,75,63,7.8,289.2,300,5.67,57,63,150,100,1.7,0.43,0.74,1800,800,0.6,24,2.65,2]', '[BountyHunter,,20,2.5,92.5,21,2.6,96.4,22,1.9,77.1,63,7,266,320,7.5,51,59,150,100,1.7,0.59,0.59,1800,1000,0.6,24,3.25,2]', '[Brewmaster,,23,3.7,130.3,19,2,77,15,1.6,61.4,57,7.3,268.7,310,2.17,52,59,150,100,1.7,0.35,0.65,1800,800,0.6,24,2.8,2]', '[Bristleback,,22,2.9,106.1,17,1.8,69.2,14,2.8,95.2,53,7.5,270.5,290,3.83,52,58,150,100,1.8,0.3,0.3,1800,800,0.9,24,2.45,2]', '[Broodmother,,18,3.2,110.8,19,3.4,117.6,18,2,76,55,8.6,304.4,280,3.17,48,54,150,125,1.7,0.4,0.5,1800,800,0.6,24,2.05,8]', '[CentaurWarrunner,,27,4.6,160.4,15,1,44,15,1.6,61.4,57,7.2,265.8,300,2.5,63,65,150,90,1.7,0.3,0.3,1800,800,0.6,24,2.95,4]', '[ChaosKnight,,22,3.2,114.8,18,1.4,58.6,18,1.2,52.8,58,5.8,226.2,325,5,51,81,150,100,1.7,0.5,0.5,1800,800,0.6,24,2.45,2]', '[Chen,,25,2,83,15,2.1,75.9,19,3.2,111.8,59,7.3,270.7,300,1.5,46,56,650,100,1.7,0.5,0.5,1800,800,0.6,24,2.75,2]', '[Clinkz,,16,2,74,22,2.5,94.5,18,2.2,81.8,56,6.7,250.3,290,3.67,37,43,600,100,1.7,0.4,0.3,1800,800,0.6,24,1.85,2]', '[Clockwerk,,26,3.5,127.5,13,2.3,79.7,18,1.5,61.5,57,7.3,268.7,310,3.17,50,52,150,100,1.7,0.33,0.64,1800,800,0.6,24,2.85,2]', '[CrystalMaiden,,18,2.2,81.8,16,1.6,62.4,16,3.3,111.7,50,7.1,255.9,280,1.67,44,50,600,100,1.7,0.45,0,1800,800,0.6,24,2.05,2]', '[DarkSeer,,20,3.1,109.9,18,1.8,70.2,21,3.1,110.9,59,8,291,295,5,54,60,150,100,1.7,0.59,0.58,1800,800,0.6,24,2.25,2]', '[DarkWillow,,20,2,78,18,1.6,64.4,21,3.5,122.5,59,7.1,264.9,290,2,48,56,475,115,1.5,0.3,1,1800,800,0.7,24,2.5,2]', '[Dawnbreaker,,26,3.6,130.4,14,1.7,63.3,20,2.2,83.8,60,7.5,277.5,310,4.33,57,61,150,100,1.7,0.46,,1800,800,0.6,24,2.85,2]', '[Dazzle,,18,2.5,90.5,20,1.7,69.3,25,3.7,132.3,63,7.9,292.1,305,3.33,47,53,575,100,1.7,0.3,0.3,1800,800,0.7,24,2.05,2]', '[DeathProphet,,21,3.1,110.9,14,1.8,66.2,24,3.3,119.7,59,8.2,296.8,325,3.33,47,57,600,100,1.7,0.5,0.51,1800,800,0.8,24,2.35,2]', '[Disruptor,,21,2.4,90.6,15,1.4,55.6,20,2.9,104.1,56,6.7,250.3,295,2.5,49,53,625,100,1.7,0.4,0.5,1800,800,0.6,24,2.35,2]', '[Doom,,24,3.7,131.3,11,0.9,37.1,15,1.7,64.3,50,6.3,232.7,285,4.83,58,68,200,100,1.9,0.5,0.7,1800,800,0.6,24,2.65,2]', '[DragonKnight,,21,3.4,119.6,19,2,77,18,1.7,67.3,58,7.1,263.9,310,3.17,53,59,150,100,1.7,0.5,0.5,1800,800,0.6,24,2.35,2]', '[DrowRanger,,18,1.9,73.1,20,2.9,104.1,15,1.4,55.6,53,6.2,232.8,295,3.33,49,56,625,100,1.7,0.5,0.3,1800,800,0.7,24,2.05,2]', '[EarthSpirit,,22,4.4,149.6,17,2.4,86.6,20,2.1,80.9,59,8.9,317.1,290,2.83,47,57,150,100,1.7,0.35,0.65,1800,800,0.6,24,2.45,2]', '[Earthshaker,,22,3.7,129.3,12,1.4,52.6,18,2.1,78.9,52,7.2,260.8,315,4,49,59,150,100,1.7,0.467,0.863,1800,800,0.9,24,3.2,2]', '[ElderTitan,,26,3,113,14,1.8,66.2,23,1.6,69.4,63,6.4,248.6,310,2.33,49,59,150,100,1.7,0.35,0.97,1800,800,0.6,24,2.85,2]', '[EmberSpirit,,21,2.6,96.4,22,2.9,106.1,20,2.2,83.8,63,7.7,286.3,305,2.67,55,59,150,100,1.7,0.4,0.3,1800,800,0.6,24,2.85,2]', '[Enchantress,,17,1.7,66.3,19,1.8,71.2,22,3.8,132.2,58,7.3,269.7,320,4.17,45,55,575,100,1.7,0.3,0.7,1800,800,0.6,24,1.95,4]', '[Enigma,,21,2.5,93.5,14,1,43,19,3.6,123.4,54,7.1,259.9,290,4.33,43,49,500,100,1.7,0.4,0.77,1800,800,0.6,24,2.35,0]', '[FacelessVoid,,20,2.4,89.6,19,3,106,15,1.5,58.5,54,6.9,254.1,300,4.17,56,62,150,100,1.7,0.5,0.56,1800,800,0.9,24,2.5,2]', '[Grimstroke,,21,2.4,90.6,18,1.9,73.1,25,3.8,135.2,64,8.1,298.9,290,3,46,50,600,100,1.7,0.35,0.85,1800,800,0.6,24,2.35,0]', '[Gyrocopter,,22,2.5,94.5,26,3.3,121.7,21,2.4,90.6,69,8.2,306.8,315,6.33,42,48,365,125,1.7,0.2,0.1,1800,800,0.6,24,2.45,2]', '[Hoodwink,,17,2,75,24,3.6,128.4,21,2.9,105.1,62,8.5,308.5,310,4,46,53,575,100,2,0.4,1.5,1800,800,0.9,8,1.95,4]', '[Huskar,,21,3.4,119.6,13,1.6,59.4,18,1.5,61.5,52,6.5,240.5,295,1.17,42,47,400,100,1.6,0.3,0.5,1800,800,0.6,24,2.35,2]', '[Invoker,,18,2.4,87.6,14,1.9,69.1,15,4.6,148.4,47,8.9,305.1,275,2.33,44,50,600,100,1.7,0.4,0.7,1800,800,0.6,24,2.05,2]', '[Io,,17,3,104,14,1.6,60.4,23,1.7,72.3,54,6.3,236.7,320,3.33,45,51,500,100,1.7,0.3,0.4,1800,800,0.7,24,1.95,0]', '[Jakiro,,27,2.8,108.2,15,1.2,49.8,26,3,113,68,7,271,290,3.5,53,61,400,100,1.7,0.4,0.3,1800,800,0.6,24,2.95,2]', '[Juggernaut,,20,2.2,83.8,34,2.8,115.2,14,1.4,54.6,68,6.4,253.6,305,5.67,50,54,150,110,1.4,0.33,0.84,1800,800,0.6,24,2.5,2]', '[KeeperoftheLight,,18,2.3,84.7,15,1.6,61.4,23,3.2,115.8,56,7.1,261.9,330,2.5,41,48,600,100,1.7,0.3,0.85,1800,800,0.6,24,2.05,2]', '[Kunkka,,24,3.8,134.2,14,1.6,60.4,18,1.8,70.2,56,7.2,264.8,315,4.33,50,60,150,100,1.7,0.4,0.3,1800,800,0.6,24,3.15,2]', '[LegionCommander,,25,3.3,120.7,18,1.7,67.3,20,2.2,83.8,63,7.2,271.8,330,3,60,64,150,100,1.7,0.46,0.64,1800,800,0.6,24,2.75,2]', '[Leshrac,,20,2.5,92.5,23,2.8,104.2,22,3.5,123.5,65,8.8,320.2,325,3.83,44,48,575,100,1.7,0.4,0.6,1800,800,0.6,24,2.25,4]', '[Lich,,20,2.1,80.9,15,2,73,24,4.1,142.9,59,8.2,296.8,295,1.5,48,57,550,100,1.7,0.46,0.54,1800,800,0.6,24,2.25,2]', '[Lifestealer,,25,2.4,94.6,19,2.6,94.4,15,1.8,67.2,59,6.8,256.2,320,4.17,47,53,150,120,1.7,0.39,0.44,1800,800,0.9,24,2.75,2]', '[Lina,,20,2.4,89.6,23,2.1,83.9,30,3.7,137.3,73,8.2,310.8,290,3.83,51,59,670,100,1.6,0.65,0.6,1800,800,0.6,24,2.25,2]', '[Lion,,18,2.2,81.8,18,1.5,61.5,18,3.5,119.5,54,7.2,262.8,290,2,47,53,600,115,1.7,0.43,0.74,1800,800,0.6,24,2.05,2]', '[LoneDruid,,18,2.5,90.5,20,2.8,101.2,13,1.4,53.6,51,6.7,245.3,325,1.33,38,42,550,100,1.6,0.33,0.53,1800,800,0.6,24,2.05,2]', '[Luna,,21,2.2,84.8,24,3.4,122.6,23,1.9,78.1,68,7.5,285.5,325,6,50,56,330,100,1.7,0.35,0.54,1800,800,0.6,24,2.6,2]', '[Lycan,,26,3.4,124.6,16,1.7,65.3,23,1.7,72.3,65,6.8,262.2,315,2.67,50,55,150,100,1.7,0.55,0.25,1800,800,0.6,8,2.85,2]', '[Magnus,,25,3.5,126.5,15,2.5,87.5,19,2.1,79.9,59,8.1,293.9,305,3.5,57,65,150,100,1.8,0.5,0.84,1800,800,0.8,24,3,4]', '[Marci,,23,3.3,118.7,20,2.4,89.6,19,1.9,74.1,62,7.6,282.4,310,3.33,56,60,150,100,1.7,0.3,0.5,1800,800,0.9,24,2.55,2]', '[Mars,,23,3.4,121.6,20,1.7,69.3,21,2.2,84.8,64,7.3,275.7,310,2.33,52,60,250,100,1.8,0.4,1.38,1800,800,0.8,24,2.55,2]', '[Medusa,,17,1.5,60.5,22,3.4,120.6,23,3.4,121.6,62,8.3,302.7,275,2.67,48,54,600,100,1.7,0.5,0.6,1800,800,0.6,24,1.95,0]', '[Meepo,,24,1.6,70.4,17,1.6,63.4,20,1.6,66.4,61,4.8,200.2,330,5.83,39,45,150,100,1.7,0.38,0.6,1800,800,0.7,8,2.65,2]', '[Mirana,,18,2.2,81.8,18,3.7,125.3,22,1.9,77.1,58,7.8,284.2,290,2,45,50,630,115,1.7,0.35,0.7,1800,800,0.6,24,2.05,2]', '[MonkeyKing,,18,2.8,99.2,22,3.7,129.3,20,1.8,72.2,60,8.3,300.7,300,5.67,51,55,300,100,1.7,0.45,0.2,1800,800,0.6,8,2.8,2]', '[Morphling,,22,3,109,24,3.9,137.1,19,1.8,71.2,65,8.7,317.3,280,2,33,42,350,100,1.5,0.5,0.5,1800,800,0.6,24,2.45,0]', '[NagaSiren,,21,2.8,102.2,21,3.3,116.7,21,2,79,63,8.1,297.9,330,6.5,44,46,150,100,1.7,0.5,0.5,1800,800,0.6,8,3.6,0]', "[Nature'sProphet,,21,2.6,96.4,22,3.6,126.4,23,3.7,130.3,66,9.9,353.1,295,3.67,50,60,600,100,1.7,0.4,0.6,1800,800,0.6,24,2.35,2]", '[Necrophos,,18,2.3,84.7,12,1.3,49.7,21,2.7,99.3,51,6.3,233.7,280,3,47,51,500,100,1.7,0.3,0.47,1800,800,0.6,24,2.05,2]', '[NightStalker,,23,3,110,18,2.3,84.7,15,1.6,61.4,56,6.9,256.1,295,5,63,67,150,100,1.7,0.55,0.55,800,1800,0.6,24,4.3,2]', '[NyxAssassin,,17,2.5,89.5,18,2.5,90.5,21,2.1,81.9,56,7.1,261.9,310,4,45,49,150,100,1.7,0.46,0.54,1800,800,0.6,24,3.7,6]', '[OgreMagi,,23,3.3,118.7,14,1.5,57.5,15,2.5,87.5,52,7.3,263.7,290,7.33,49,55,150,100,1.7,0.3,0.3,1800,800,0.6,24,5.55,2]', '[Omniknight,,23,3.1,112.9,15,2,73,15,1.8,67.2,53,6.9,253.1,315,4.5,54,64,150,100,1.7,0.433,0.567,1800,800,0.6,24,2.55,2]', '[Oracle,,20,2.4,89.6,15,1.7,64.3,26,3.8,136.2,61,7.9,290.1,295,3.5,39,45,620,100,1.7,0.3,0.7,1800,800,0.7,24,2.25,0]', '[OutworldDestroyer,,21,2.9,105.1,22,1.6,68.4,30,4.2,151.8,73,8.7,325.3,320,6.17,49,61,450,100,1.9,0.46,0.54,1800,800,0.6,24,3.1,4]', '[Pangolier,,17,2.5,89.5,18,3.2,110.8,16,1.9,71.1,51,7.6,271.4,300,4,51,57,150,100,1.7,0.33,0.77,1800,800,0.9,24,1.95,2]', '[PhantomAssassin,,21,2.2,84.8,23,3.4,121.6,15,1.4,55.6,59,7,262,305,4.83,55,57,150,100,1.7,0.3,0.7,1800,800,0.6,24,2.85,2]', '[PhantomLancer,,19,2.2,82.8,26,3.2,118.8,21,2,79,66,7.4,280.6,290,3.33,52,62,150,100,1.7,0.5,0.5,1800,800,0.6,8,3.4,2]', '[Phoenix,,23,3.5,124.5,12,1.3,49.7,16,1.8,68.2,51,6.6,242.4,280,1,49,59,525,100,1.7,0.35,0.633,1800,800,0.9,24,3.3,2]', '[Puck,,17,2.4,86.6,22,2.5,94.5,23,3.5,124.5,62,8.4,305.6,290,0.67,45,53,550,100,1.7,0.5,0.8,1800,800,0.8,24,2.2,2]', '[Pudge,,25,3,112,14,1.4,54.6,16,1.5,59.5,55,5.9,226.1,280,2.33,67,73,175,100,1.7,0.5,1.17,1800,800,0.7,24,4.5,2]', '[Pugna,,19,2,77,24,1.3,61.7,24,5.2,174.8,67,8.5,313.5,330,4,45,52,630,100,1.7,0.5,0.5,1800,800,0.6,24,2.15,2]', '[QueenofPain,,18,2.4,87.6,22,2.5,94.5,25,3.4,123.6,65,8.3,305.7,290,3.67,49,55,550,100,1.5,0.56,0.41,1800,800,0.6,24,2.05,2]', '[Razor,,22,2.8,103.2,22,2.6,97.4,21,2.2,84.8,65,7.6,285.4,290,2.67,45,47,475,100,1.7,0.3,0.4,1800,800,0.6,24,3.2,0]', '[Riki,,18,2.4,87.6,18,1.4,58.6,14,1.3,51.7,50,5.1,197.9,320,6,59,63,150,100,1.7,0.3,0.3,1800,800,0.6,24,4.3,2]', '[Rubick,,21,2,79,23,2.5,95.5,25,3.1,114.9,69,7.6,289.4,290,3.83,49,55,550,100,1.7,0.4,0.77,1800,800,0.7,24,2.35,2]', '[SandKing,,22,2.7,100.3,19,1.8,71.2,19,1.8,71.2,60,6.3,242.7,290,2.17,45,55,150,110,1.7,0.53,0.47,1800,800,0.6,24,2.45,6]', '[ShadowDemon,,23,2.6,98.4,18,2.2,81.8,22,3.6,126.4,63,8.4,306.6,290,3,51,55,500,100,1.7,0.35,0.5,1800,800,0.6,24,2.55,2]', '[ShadowFiend,,19,2.7,97.3,20,3.5,121.5,18,2.2,81.8,57,8.4,300.6,305,4.33,39,45,500,100,1.6,0.5,0.54,1800,800,0.9,24,2.15,0]', '[ShadowShaman,,23,2.3,89.7,16,1.6,62.4,25,3.5,126.5,64,7.4,278.6,285,4.67,71,78,400,90,1.7,0.3,0.5,1800,800,0.6,24,3.3,2]', '[Silencer,,19,2.4,88.6,22,2.4,91.6,25,2.9,109.1,66,7.7,289.3,290,2.67,43,57,600,115,1.7,0.5,0.5,1800,800,0.6,24,2.15,2]', '[SkywrathMage,,21,2,79,13,0.8,36.2,25,4.1,143.9,59,6.9,259.1,325,0.17,41,51,625,100,1.7,0.4,0.78,1800,800,0.6,24,2.35,2]', '[Slardar,,21,3.6,125.4,17,2.4,86.6,15,1.5,58.5,53,7.5,270.5,300,5.83,51,59,150,100,1.7,0.36,0.64,1800,800,0.6,24,2.6,0]', '[Slark,,21,1.9,76.1,21,1.7,70.3,16,1.7,65.3,58,5.3,211.7,300,3.5,53,61,150,110,1.7,0.5,0.3,1800,1800,0.7,24,3.85,2]', '[Snapfire,,20,3.5,121.5,16,1.9,71.1,21,2.2,84.8,57,7.6,277.4,300,3.67,46,52,500,100,1.6,0.35,1.23,1800,800,0.6,24,2.75,2]', '[Sniper,,19,2,77,27,3.2,119.8,15,2.6,90.4,61,7.8,287.2,285,3.5,40,46,550,100,1.7,0.17,0.7,1800,1400,0.7,24,2.15,2]', '[Spectre,,23,2.5,95.5,23,2.1,83.9,16,1.9,71.1,62,6.5,250.5,290,4.83,46,50,150,90,1.7,0.3,0.7,1800,800,0.6,24,3.8,0]', '[SpiritBreaker,,28,3,115,17,1.7,66.3,14,1.8,66.2,59,6.5,247.5,295,4.83,59,69,150,100,1.9,0.6,0.3,1800,800,0.6,24,4.05,2]', '[StormSpirit,,21,2,79,22,1.7,71.3,23,3.9,136.1,66,7.6,286.4,285,5.67,47,57,480,110,1.7,0.5,0.3,1800,800,0.8,24,2.35,2]', '[Sven,,22,3.2,114.8,21,2,79,16,1.3,53.7,59,6.5,247.5,325,3.5,63,65,150,100,1.9,0.4,0.3,1800,800,0.6,24,2.45,2]', '[Techies,,19,2.5,91.5,14,1.3,51.7,25,3.3,120.7,58,7.1,263.9,320,7.33,34,36,700,90,1.7,0.5,0.5,1800,800,0.6,24,2.15,6]', '[TemplarAssassin,,21,2.4,90.6,23,3.2,115.8,20,2,78,64,7.6,284.4,305,4.83,53,59,160,100,1.7,0.3,0.5,1800,800,0.7,24,2.35,2]', '[Terrorblade,,16,2,74,22,4.4,149.6,19,1.6,65.4,57,8,289,315,8.67,52,58,150,100,1.5,0.3,0.6,1800,800,0.6,24,2.6,2]', '[Tidehunter,,27,3.5,128.5,15,1.5,58.5,18,1.7,67.3,60,6.7,254.3,300,2.5,52,58,150,100,1.7,0.6,0.56,1800,800,0.6,24,2.95,2]', '[Timbersaw,,24,3.2,116.8,16,1.6,62.4,23,2.7,101.3,63,7.5,280.5,290,2.67,51,55,150,100,1.7,0.36,0.64,1800,800,0.6,24,2.65,2]', '[Tinker,,18,2.5,90.5,13,1.2,47.8,30,3.3,125.7,61,7,264,290,4.17,54,60,500,100,1.7,0.35,0.65,1800,800,0.6,24,2.05,2]', '[Tiny,,30,4,146,0,0,0,17,2.2,80.8,47,6.2,226.8,295,0,61,67,150,90,1.7,0.4,0.7,1800,800,0.6,24,4.5,2]', '[TreantProtector,,25,3.4,123.6,15,2,73,20,1.8,72.2,60,7.2,268.8,285,1.5,87,95,150,100,1.9,0.6,0.4,1800,800,0.6,24,2.75,2]', '[TrollWarlord,,21,2.5,93.5,21,3.3,116.7,13,1,42,55,6.8,252.2,290,2.5,48,56,500,100,1.7,0.3,0.3,1800,800,0.6,24,2.35,2]', '[Tusk,,23,3.9,136.1,23,2.1,83.9,18,1.7,67.3,64,7.7,287.3,315,4.83,50,54,150,100,1.7,0.36,0.64,1800,800,0.7,24,3.05,2]', '[Underlord,,25,3,112,12,1.6,58.4,17,2.3,83.7,54,6.9,254.1,290,5,62,68,200,100,1.7,0.45,0.7,1800,800,0.6,24,2.75,2]', '[Undying,,22,2.8,103.2,10,1.2,44.8,27,2.8,108.2,59,6.8,256.2,300,2.67,57,65,150,100,1.7,0.3,0.3,1800,800,0.6,24,2.45,2]', '[Ursa,,25,2.6,100.4,18,2.6,93.4,16,1.5,59.5,59,6.7,253.3,310,4,42,46,150,100,1.7,0.3,0.3,1800,800,0.6,24,3,2]', '[VengefulSpirit,,19,2.6,94.4,20,3.2,112.8,19,1.5,62.5,58,7.3,269.7,295,3.33,44,50,400,100,1.7,0.33,0.64,1800,800,0.6,24,2.15,2]', '[Venomancer,,19,2.1,79.9,24,2.8,105.2,19,1.8,71.2,62,6.7,256.3,280,4,42,45,450,115,1.7,0.3,0.7,1800,800,0.6,24,2.15,0]', '[Viper,,21,2.4,90.6,21,2.7,99.3,17,2,75,59,7.1,264.9,275,1.5,48,50,575,120,1.7,0.33,1,1800,800,0.6,24,2.35,0]', '[Visage,,22,2.8,103.2,11,1.3,48.7,22,2.9,106.1,55,7,258,285,0.83,45,55,600,110,1.7,0.4,0.54,1800,800,0.6,24,2.45,2]', '[VoidSpirit,,22,2.6,97.4,19,2.2,82.8,24,3.1,113.9,65,7.9,294.1,295,2.17,54,58,200,100,1.7,0.35,0.78,1800,800,0.7,24,2.45,2]', '[Warlock,,24,3,111,10,1,39,25,3.1,114.9,59,7.1,264.9,290,2.67,49,59,600,100,1.7,0.3,0.3,1800,800,0.6,24,2.65,2]', '[Weaver,,16,2,74,17,3.1,106.9,20,2,78,53,7.1,258.9,275,2.83,54,60,425,120,1.8,0.55,0.36,1800,800,0.6,24,2.85,4]', '[Windranger,,18,3,105,17,1.4,57.6,18,3.6,122.4,53,8,285,290,1.83,42,54,600,100,1.5,0.4,0.3,1800,800,0.8,24,2.05,2]', '[WinterWyvern,,24,2.6,99.4,16,1.7,65.3,26,3.6,130.4,66,7.9,295.1,285,2.67,40,47,425,100,1.7,0.25,0.8,1800,800,0.6,24,2.65,2]', '[WitchDoctor,,18,2.3,84.7,13,1.4,53.6,22,3.3,117.7,53,7,256,300,2.17,51,61,600,100,1.7,0.4,0.5,1800,800,0.6,24,2.05,2]', '[WraithKing,,22,3,109,18,1.7,67.3,18,1.6,64.4,58,6.3,240.7,315,2,60,62,150,100,1.7,0.56,0.44,1800,800,0.6,24,2.45,2]', '[Zeus,,19,2.1,79.9,11,1.2,45.8,22,3.3,117.7,52,6.6,243.4,315,3.83,55,63,380,100,1.7,0.35,0.55,1800,800,0.6,24,2.15,2]', '[v\xa0•\xa0d\xa0•\xa0eMechanicsStatsArmorAttributes(Strength/Agility/Intelligence)CollisionsizeHealth(Healthregeneration)MagicresistanceMana(Manaregeneration)MovementspeedStatusresistanceTurnrateVisionGibtypeLegsAttackAttackanimationAttackdamage(Heroes)Attackmodifier(Bash/Cleave&Splash/Criticalstrike/Lifesteal/Manabreak)AttackrangeAttackspeedCastanimationCastrangeDamagetypesProjectilespeedSpelldamageSpelllifestealAbilitiesAbilitiesAuraChannelingCooldownDamageblockDamagemanipulationDamageovertimeEvasionTalentsTeleportStatuseffectsAttackimmunityBreakCycloneDisableDisarmEtherealFearForcedmovementHexHideHypnosisInvisibilityInvulnerabilityLeashPhasedRootSilenceSleepSlowSpellimmunityStunTauntWorldExperienceGoldGlyphofFortificationMap(Minimap)RiverScanRunesTimeofdayTreesGameplayCreepcontroltechniquesDenyingDisjointDispelGankingHarassmentHerocomplexityInitiatingItempassivestackingItemsharingJunglingLanePushingRandomdistributionRolesTrapUnitsAncientcreepsBuildingsCouriersCreep-heroesHeroesIllusionsLanecreepsNeutralcreepsRoshanSummons&Wards,,Stats,ArmorAttributes(Strength/Agility/Intelligence)CollisionsizeHealth(Healthregeneration)MagicresistanceMana(Manaregeneration)MovementspeedStatusresistanceTurnrateVisionGibtypeLegs,,Attack,AttackanimationAttackdamage(Heroes)Attackmodifier(Bash/Cleave&Splash/Criticalstrike/Lifesteal/Manabreak)AttackrangeAttackspeedCastanimationCastrangeDamagetypesProjectilespeedSpelldamageSpelllifesteal,,Abilities,AbilitiesAuraChannelingCooldownDamageblockDamagemanipulationDamageovertimeEvasionTalentsTeleport,,Statuseffects,AttackimmunityBreakCycloneDisableDisarmEtherealFearForcedmovementHexHideHypnosisInvisibilityInvulnerabilityLeashPhasedRootSilenceSleepSlowSpellimmunityStunTaunt,,World,ExperienceGoldGlyphofFortificationMap(Minimap)RiverScanRunesTimeofdayTrees,,Gameplay,CreepcontroltechniquesDenyingDisjointDispelGankingHarassmentHerocomplexityInitiatingItempassivestackingItemsharingJunglingLanePushingRandomdistributionRolesTrap,,Units,AncientcreepsBuildingsCouriersCreep-heroesHeroesIllusionsLanecreepsNeutralcreepsRoshanSummons&Wards]', '[]', '[]', '[Stats,ArmorAttributes(Strength/Agility/Intelligence)CollisionsizeHealth(Healthregeneration)MagicresistanceMana(Manaregeneration)MovementspeedStatusresistanceTurnrateVisionGibtypeLegs]', '[]', '[Attack,AttackanimationAttackdamage(Heroes)Attackmodifier(Bash/Cleave&Splash/Criticalstrike/Lifesteal/Manabreak)AttackrangeAttackspeedCastanimationCastrangeDamagetypesProjectilespeedSpelldamageSpelllifesteal]', '[]', '[Abilities,AbilitiesAuraChannelingCooldownDamageblockDamagemanipulationDamageovertimeEvasionTalentsTeleport]', '[]', '[Statuseffects,AttackimmunityBreakCycloneDisableDisarmEtherealFearForcedmovementHexHideHypnosisInvisibilityInvulnerabilityLeashPhasedRootSilenceSleepSlowSpellimmunityStunTaunt]', '[]', '[World,ExperienceGoldGlyphofFortificationMap(Minimap)RiverScanRunesTimeofdayTrees]', '[]', '[Gameplay,CreepcontroltechniquesDenyingDisjointDispelGankingHarassmentHerocomplexityInitiatingItempassivestackingItemsharingJunglingLanePushingRandomdistributionRolesTrap]', '[]', '[Units,AncientcreepsBuildingsCouriersCreep-heroesHeroesIllusionsLanecreepsNeutralcreepsRoshanSummons&Wards]']

the content of table are written in numpy array

In [5]:
#convert the numpy arrray to dataframe
contents = pd.DataFrame(all_rows)
contents.tail(5)

                                                     0
134  [World,ExperienceGoldGlyphofFortificationMap(M...
135                                                 []
136  [Gameplay,CreepcontroltechniquesDenyingDisjoin...
137                                                 []
138  [Units,AncientcreepsBuildingsCouriersCreep-her...

In [6]:
contents = contents[0].str.split(',', expand=True)
contents

                     0   ...    28
0                    []  ...  None
1              [Abaddon  ...    2]
2            [Alchemist  ...    2]
3    [AncientApparition  ...    0]
4            [Anti-Mage  ...    2]
..                  ...  ...   ...
134              [World  ...  None
135                  []  ...  None
136           [Gameplay  ...  None
137                  []  ...  None
138              [Units  ...  None

[139 rows x 29 columns]

In [7]:
contents[0] = contents[0].str.strip('[]')
contents

                    0   ...    28
0                       ...  None
1              Abaddon  ...    2]
2            Alchemist  ...    2]
3    AncientApparition  ...    0]
4            Anti-Mage  ...    2]
..                 ...  ...   ...
134              World  ...  None
135                     ...  None
136           Gameplay  ...  None
137                     ...  None
138              Units  ...  None

[139 rows x 29 columns]

In [8]:
contents[28] = contents[28].str.strip('[]')
contents

                    0   ...    28
0                       ...  None
1              Abaddon  ...     2
2            Alchemist  ...     2
3    AncientApparition  ...     0
4            Anti-Mage  ...     2
..                 ...  ...   ...
134              World  ...  None
135                     ...  None
136           Gameplay  ...  None
137                     ...  None
138              Units  ...  None

[139 rows x 29 columns]

In [9]:
#Because there is unused rows in rows 123 to 138
#Drop the unused rows
contents = contents.drop(contents.index[123:])
contents

                    0     1     2     3      4   ...    24    25    26    27    28
0                       None  None  None   None  ...  None  None  None  None  None
1              Abaddon          22   2.8  103.2  ...   800   0.6    24   3.2     2
2            Alchemist          25   2.9  109.1  ...   800   0.6    24  2.75     2
3    AncientApparition          20   1.9   75.1  ...   800   0.6    24  2.25     0
4            Anti-Mage          23   1.6   69.4  ...   800   0.6    24  2.55     2
..                 ...   ...   ...   ...    ...  ...   ...   ...   ...   ...   ...
118         Windranger          18     3    105  ...   800   0.8    24  2.05     2
119       WinterWyvern          24   2.6   99.4  ...   800   0.6    24  2.65     2
120        WitchDoctor          18   2.3   84.7  ...   800   0.6    24  2.05     2
121         WraithKing          22     3    109  ...   800   0.6    24  2.45     2
122               Zeus          19   2.1   79.9  ...   800   0.6    24  2.15     2

[123 rows x 29 columns]

In [10]:
#drop the first cow with None value
contents = contents.drop(contents.index[0])
contents

                    0  1   2    3      4   5   ...    23   24   25  26    27 28
1              Abaddon     22  2.8  103.2  23  ...  1800  800  0.6  24   3.2  2
2            Alchemist     25  2.9  109.1  22  ...  1800  800  0.6  24  2.75  2
3    AncientApparition     20  1.9   75.1  20  ...  1800  800  0.6  24  2.25  0
4            Anti-Mage     23  1.6   69.4  24  ...  1800  800  0.6  24  2.55  2
5            ArcWarden     22  2.6   97.4  20  ...  1800  800  0.7  24  2.45  2
..                 ... ..  ..  ...    ...  ..  ...   ...  ...  ...  ..   ... ..
118         Windranger     18    3    105  17  ...  1800  800  0.8  24  2.05  2
119       WinterWyvern     24  2.6   99.4  16  ...  1800  800  0.6  24  2.65  2
120        WitchDoctor     18  2.3   84.7  13  ...  1800  800  0.6  24  2.05  2
121         WraithKing     22    3    109  18  ...  1800  800  0.6  24  2.45  2
122               Zeus     19  2.1   79.9  11  ...  1800  800  0.6  24  2.15  2

[122 rows x 29 columns]

In [11]:
#Scrapping the header for heroes attributes
col_labels = soup.find_all('th')
hero_header = []
col_name = str(col_labels)
col_name = col_name.replace('\r', '')
col_name = col_name.replace(' ', '')
col_name = col_name.replace('\n', '')
col_name = col_name.replace('[', '')
col_name = col_name.replace(']', '')
cleantext2 = BeautifulSoup(col_name, 'lxml').get_text()
hero_header.append(cleantext2)
print(hero_header)

['HERO,A,STR,STR+,STR30,AGI,AGI+,AGI30,INT,INT+,INT30,T,T+,T30,MS,AR,DMG(MIN),DMG(MAX),RG,AS,BAT,ATKPT,ATKBS,VS-D,VS-N,TR,COL,HP/S,L,v\xa0•\xa0d\xa0•\xa0eMechanics']

In [12]:
#convert numpy array into dataframe
headers = pd.DataFrame(hero_header)
headers

                                                   0
0  HERO,A,STR,STR+,STR30,AGI,AGI+,AGI30,INT,INT+,...

In [13]:
#split the string with ','
headers = headers[0].str.split(',', expand=True)
headers

     0  1    2     3      4    5   ...    24  25   26    27 28                  29
0  HERO  A  STR  STR+  STR30  AGI  ...  VS-N  TR  COL  HP/S  L  v • d • eMechanics

[1 rows x 30 columns]

In [14]:
#merge the content and headers
frames = [headers, contents]
final = pd.concat(frames)
final

                    0  1    2     3   ...   26    27 28                  29
0                 HERO  A  STR  STR+  ...  COL  HP/S  L  v • d • eMechanics
1              Abaddon      22   2.8  ...   24   3.2  2                 NaN
2            Alchemist      25   2.9  ...   24  2.75  2                 NaN
3    AncientApparition      20   1.9  ...   24  2.25  0                 NaN
4            Anti-Mage      23   1.6  ...   24  2.55  2                 NaN
..                 ... ..  ...   ...  ...  ...   ... ..                 ...
118         Windranger      18     3  ...   24  2.05  2                 NaN
119       WinterWyvern      24   2.6  ...   24  2.65  2                 NaN
120        WitchDoctor      18   2.3  ...   24  2.05  2                 NaN
121         WraithKing      22     3  ...   24  2.45  2                 NaN
122               Zeus      19   2.1  ...   24  2.15  2                 NaN

[123 rows x 30 columns]

In [15]:
#make the first row to column name
final = final.rename(columns=final.iloc[0])
final

                  HERO  A  STR  STR+  ...  COL  HP/S  L  v • d • eMechanics
0                 HERO  A  STR  STR+  ...  COL  HP/S  L  v • d • eMechanics
1              Abaddon      22   2.8  ...   24   3.2  2                 NaN
2            Alchemist      25   2.9  ...   24  2.75  2                 NaN
3    AncientApparition      20   1.9  ...   24  2.25  0                 NaN
4            Anti-Mage      23   1.6  ...   24  2.55  2                 NaN
..                 ... ..  ...   ...  ...  ...   ... ..                 ...
118         Windranger      18     3  ...   24  2.05  2                 NaN
119       WinterWyvern      24   2.6  ...   24  2.65  2                 NaN
120        WitchDoctor      18   2.3  ...   24  2.05  2                 NaN
121         WraithKing      22     3  ...   24  2.45  2                 NaN
122               Zeus      19   2.1  ...   24  2.15  2                 NaN

[123 rows x 30 columns]

In [16]:
#drop unused rows
final = final.drop(final.index[0])

#drop unused columns
final.drop(final.columns[29], axis = 1, inplace=True)
final.drop('A', axis=1, inplace=True)

#check the final data
final

                  HERO STR STR+  STR30 AGI AGI+  ...  VS-D VS-N   TR COL  HP/S  L
1              Abaddon  22  2.8  103.2  23  1.5  ...  1800  800  0.6  24   3.2  2
2            Alchemist  25  2.9  109.1  22  1.5  ...  1800  800  0.6  24  2.75  2
3    AncientApparition  20  1.9   75.1  20  2.2  ...  1800  800  0.6  24  2.25  0
4            Anti-Mage  23  1.6   69.4  24  2.8  ...  1800  800  0.6  24  2.55  2
5            ArcWarden  22  2.6   97.4  20  2.5  ...  1800  800  0.7  24  2.45  2
..                 ...  ..  ...    ...  ..  ...  ...   ...  ...  ...  ..   ... ..
118         Windranger  18    3    105  17  1.4  ...  1800  800  0.8  24  2.05  2
119       WinterWyvern  24  2.6   99.4  16  1.7  ...  1800  800  0.6  24  2.65  2
120        WitchDoctor  18  2.3   84.7  13  1.4  ...  1800  800  0.6  24  2.05  2
121         WraithKing  22    3    109  18  1.7  ...  1800  800  0.6  24  2.45  2
122               Zeus  19  2.1   79.9  11  1.2  ...  1800  800  0.6  24  2.15  2

[122 rows x 28 columns]

In [17]:
#Scrapping the for additional columns 'MAINATT' (MAINATT is on images)
import urllib.request

thepage = urllib.request.urlopen(url)
sup = BeautifulSoup(thepage)

raw_att = [i['title'] for i in soup.find_all('a', title=True)]
print(raw_att)

['Search', 'Dark Theme', 'Search', 'Search', 'Dark Theme', 'Heroes', 'Heroes/Introductions', 'Heroes/Mechanics', 'Heroes by release', 'Hero Grid', 'Cast animation', 'Abaddon', 'Abaddon', 'Strength', 'Alchemist', 'Alchemist', 'Strength', 'Ancient Apparition', 'Ancient Apparition', 'Intelligence', 'Anti-Mage', 'Anti-Mage', 'Agility', 'Arc Warden', 'Arc Warden', 'Agility', 'Axe', 'Axe', 'Strength', 'Bane', 'Bane', 'Intelligence', 'Batrider', 'Batrider', 'Intelligence', 'Beastmaster', 'Beastmaster', 'Strength', 'Bloodseeker', 'Bloodseeker', 'Agility', 'Bounty Hunter', 'Bounty Hunter', 'Agility', 'Brewmaster', 'Brewmaster', 'Strength', 'Bristleback', 'Bristleback', 'Strength', 'Broodmother', 'Broodmother', 'Agility', 'Centaur Warrunner', 'Centaur Warrunner', 'Strength', 'Chaos Knight', 'Chaos Knight', 'Strength', 'Chen', 'Chen', 'Intelligence', 'Clinkz', 'Clinkz', 'Agility', 'Clockwerk', 'Clockwerk', 'Strength', 'Crystal Maiden', 'Crystal Maiden', 'Intelligence', 'Dark Seer', 'Dark Seer', 'Intelligence', 'Dark Willow', 'Dark Willow', 'Intelligence', 'Dawnbreaker', 'Dawnbreaker', 'Strength', 'Dazzle', 'Dazzle', 'Intelligence', 'Death Prophet', 'Death Prophet', 'Intelligence', 'Disruptor', 'Disruptor', 'Intelligence', 'Doom', 'Doom', 'Strength', 'Dragon Knight', 'Dragon Knight', 'Strength', 'Drow Ranger', 'Drow Ranger', 'Agility', 'Earth Spirit', 'Earth Spirit', 'Strength', 'Earthshaker', 'Earthshaker', 'Strength', 'Elder Titan', 'Elder Titan', 'Strength', 'Ember Spirit', 'Ember Spirit', 'Agility', 'Enchantress', 'Enchantress', 'Intelligence', 'Enigma', 'Enigma', 'Intelligence', 'Faceless Void', 'Faceless Void', 'Agility', 'Grimstroke', 'Grimstroke', 'Intelligence', 'Gyrocopter', 'Gyrocopter', 'Agility', 'Hoodwink', 'Hoodwink', 'Agility', 'Huskar', 'Huskar', 'Strength', 'Invoker', 'Invoker', 'Intelligence', 'Io', 'Io', 'Strength', 'Jakiro', 'Jakiro', 'Intelligence', 'Juggernaut', 'Juggernaut', 'Agility', 'Keeper of the Light', 'Keeper of the Light', 'Intelligence', 'Kunkka', 'Kunkka', 'Strength', 'Legion Commander', 'Legion Commander', 'Strength', 'Leshrac', 'Leshrac', 'Intelligence', 'Lich', 'Lich', 'Intelligence', 'Lifestealer', 'Lifestealer', 'Strength', 'Lina', 'Lina', 'Intelligence', 'Lion', 'Lion', 'Intelligence', 'Lone Druid', 'Lone Druid', 'Agility', 'Luna', 'Luna', 'Agility', 'Lycan', 'Lycan', 'Strength', 'Magnus', 'Magnus', 'Strength', 'Marci', 'Marci', 'Strength', 'Mars', 'Mars', 'Strength', 'Medusa', 'Medusa', 'Agility', 'Meepo', 'Meepo', 'Agility', 'Mirana', 'Mirana', 'Agility', 'Monkey King', 'Monkey King', 'Agility', 'Morphling', 'Morphling', 'Agility', 'Naga Siren', 'Naga Siren', 'Agility', "Nature's Prophet", "Nature's Prophet", 'Intelligence', 'Necrophos', 'Necrophos', 'Intelligence', 'Night Stalker', 'Night Stalker', 'Strength', 'Nyx Assassin', 'Nyx Assassin', 'Agility', 'Ogre Magi', 'Ogre Magi', 'Intelligence', 'Omniknight', 'Omniknight', 'Strength', 'Oracle', 'Oracle', 'Intelligence', 'Outworld Destroyer', 'Outworld Destroyer', 'Intelligence', 'Pangolier', 'Pangolier', 'Agility', 'Phantom Assassin', 'Phantom Assassin', 'Agility', 'Phantom Lancer', 'Phantom Lancer', 'Agility', 'Phoenix', 'Phoenix', 'Strength', 'Puck', 'Puck', 'Intelligence', 'Pudge', 'Pudge', 'Strength', 'Pugna', 'Pugna', 'Intelligence', 'Queen of Pain', 'Queen of Pain', 'Intelligence', 'Razor', 'Razor', 'Agility', 'Riki', 'Riki', 'Agility', 'Rubick', 'Rubick', 'Intelligence', 'Sand King', 'Sand King', 'Strength', 'Shadow Demon', 'Shadow Demon', 'Intelligence', 'Shadow Fiend', 'Shadow Fiend', 'Agility', 'Shadow Shaman', 'Shadow Shaman', 'Intelligence', 'Silencer', 'Silencer', 'Intelligence', 'Skywrath Mage', 'Skywrath Mage', 'Intelligence', 'Slardar', 'Slardar', 'Strength', 'Slark', 'Slark', 'Agility', 'Snapfire', 'Snapfire', 'Strength', 'Sniper', 'Sniper', 'Agility', 'Spectre', 'Spectre', 'Agility', 'Spirit Breaker', 'Spirit Breaker', 'Strength', 'Storm Spirit', 'Storm Spirit', 'Intelligence', 'Sven', 'Sven', 'Strength', 'Techies', 'Techies', 'Intelligence', 'Templar Assassin', 'Templar Assassin', 'Agility', 'Terrorblade', 'Terrorblade', 'Agility', 'Tidehunter', 'Tidehunter', 'Strength', 'Timbersaw', 'Timbersaw', 'Strength', 'Tinker', 'Tinker', 'Intelligence', 'Tiny', 'Tiny', 'Strength', 'Treant Protector', 'Treant Protector', 'Strength', 'Troll Warlord', 'Troll Warlord', 'Agility', 'Tusk', 'Tusk', 'Strength', 'Underlord', 'Underlord', 'Strength', 'Undying', 'Undying', 'Strength', 'Ursa', 'Ursa', 'Agility', 'Vengeful Spirit', 'Vengeful Spirit', 'Agility', 'Venomancer', 'Venomancer', 'Agility', 'Viper', 'Viper', 'Agility', 'Visage', 'Visage', 'Intelligence', 'Void Spirit', 'Void Spirit', 'Intelligence', 'Warlock', 'Warlock', 'Intelligence', 'Weaver', 'Weaver', 'Agility', 'Windranger', 'Windranger', 'Intelligence', 'Winter Wyvern', 'Winter Wyvern', 'Intelligence', 'Witch Doctor', 'Witch Doctor', 'Intelligence', 'Wraith King', 'Wraith King', 'Strength', 'Zeus', 'Zeus', 'Intelligence', 'Mechanics', 'Armor', 'Attributes', 'Strength', 'Strength', 'Agility', 'Agility', 'Intelligence', 'Intelligence', 'Collision size', 'Health', 'Health regeneration', 'Magic resistance', 'Mana', 'Mana regeneration', 'Movement speed', 'Status resistance', 'Turn rate', 'Vision', 'Gib type', 'Legs', 'Attack animation', 'Attack damage', 'Attack Damage/Heroes', 'Attack modifier', 'Bash', 'Cleave', 'Critical strike', 'Lifesteal', 'Mana break', 'Attack range', 'Attack speed', 'Cast animation', 'Cast range', 'Damage types', 'Projectile speed', 'Spell damage', 'Spell lifesteal', 'Abilities', 'Aura', 'Channeling', 'Cooldown', 'Damage block', 'Damage manipulation', 'Damage over time', 'Evasion', 'Talents', 'Teleport', 'Attack immunity', 'Break', 'Cyclone', 'Disable', 'Disarm', 'Ethereal', 'Fear', 'Forced movement', 'Hex', 'Hide', 'Hypnosis', 'Invisibility', 'Invulnerability', 'Leash', 'Collision size', 'Root', 'Silence', 'Sleep', 'Slow', 'Spell immunity', 'Stun', 'Taunt', 'Experience', 'Gold', 'Glyph of Fortification', 'Map', 'Minimap', 'River', 'Scan', 'Runes', 'Time of day', 'Trees', 'Creep control techniques', 'Denying', 'Disjoint', 'Dispel', 'Ganking', 'Harassment', 'Hero complexity', 'Initiating', 'Item passive stacking', 'Item sharing', 'Jungling', 'Lane', 'Pushing', 'Random distribution', 'Role', 'Trap', 'Ancient (unit type)', 'Buildings', 'Courier', 'Creep-heroes', 'Heroes/Mechanics', 'Illusions', 'Lane creeps', 'Neutral creeps', 'Roshan', 'Summons', 'Special:Categories', "Aghanim's Labyrinth: The Continuum Conundrum", 'Heroes', 'Items', 'Universal Conquest Wiki', "Let's Go Luna! Wiki", 'Club 57 Wiki', 'Fandom']

In [18]:
#convert the numpy arrray to dataframe
raw_att = pd.DataFrame(raw_att)
raw_att

                           0
0                     Search
1                 Dark Theme
2                     Search
3                     Search
4                 Dark Theme
..                       ...
486                    Items
487  Universal Conquest Wiki
488      Let's Go Luna! Wiki
489             Club 57 Wiki
490                   Fandom

[491 rows x 1 columns]

In [19]:
#Because there is unused rows in rows 377 to end
#Drop the unused rows
raw_att = raw_att.drop(raw_att.index[377:])
raw_att

                0
0          Search
1      Dark Theme
2          Search
3          Search
4      Dark Theme
..            ...
372   Wraith King
373      Strength
374          Zeus
375          Zeus
376  Intelligence

[377 rows x 1 columns]

In [20]:
#Because there is unused rows in rows first to 10
#Drop the unused rows
raw_att = raw_att.drop(raw_att.index[:11])
raw_att

                0
11        Abaddon
12        Abaddon
13       Strength
14      Alchemist
15      Alchemist
..            ...
372   Wraith King
373      Strength
374          Zeus
375          Zeus
376  Intelligence

[366 rows x 1 columns]

In [21]:
#define the reference list to filter raw_att
list_att = ['Strength', 'Agility', 'Intelligence']
list_att = pd.DataFrame(list_att)
list_att

              0
0      Strength
1       Agility
2  Intelligence

In [22]:
#check if the list in list_att, the value will be assign in the list prim_att
prim_att = raw_att[raw_att[0].isin(list_att[0])]

#reindexing from 1
prim_att.index = np.arange(1, len(prim_att)+1)

prim_att

                0
1        Strength
2        Strength
3    Intelligence
4         Agility
5         Agility
..            ...
118  Intelligence
119  Intelligence
120  Intelligence
121      Strength
122  Intelligence

[122 rows x 1 columns]

In [23]:
#add column 'Attribute'
final['Attribute'] = prim_att
final

                  HERO STR STR+  STR30 AGI  ...   TR COL  HP/S  L     Attribute
1              Abaddon  22  2.8  103.2  23  ...  0.6  24   3.2  2      Strength
2            Alchemist  25  2.9  109.1  22  ...  0.6  24  2.75  2      Strength
3    AncientApparition  20  1.9   75.1  20  ...  0.6  24  2.25  0  Intelligence
4            Anti-Mage  23  1.6   69.4  24  ...  0.6  24  2.55  2       Agility
5            ArcWarden  22  2.6   97.4  20  ...  0.7  24  2.45  2       Agility
..                 ...  ..  ...    ...  ..  ...  ...  ..   ... ..           ...
118         Windranger  18    3    105  17  ...  0.8  24  2.05  2  Intelligence
119       WinterWyvern  24  2.6   99.4  16  ...  0.6  24  2.65  2  Intelligence
120        WitchDoctor  18  2.3   84.7  13  ...  0.6  24  2.05  2  Intelligence
121         WraithKing  22    3    109  18  ...  0.6  24  2.45  2      Strength
122               Zeus  19  2.1   79.9  11  ...  0.6  24  2.15  2  Intelligence

[122 rows x 29 columns]

In [24]:
#define the clean dataframe
df = final.copy()
df

                  HERO STR STR+  STR30 AGI  ...   TR COL  HP/S  L     Attribute
1              Abaddon  22  2.8  103.2  23  ...  0.6  24   3.2  2      Strength
2            Alchemist  25  2.9  109.1  22  ...  0.6  24  2.75  2      Strength
3    AncientApparition  20  1.9   75.1  20  ...  0.6  24  2.25  0  Intelligence
4            Anti-Mage  23  1.6   69.4  24  ...  0.6  24  2.55  2       Agility
5            ArcWarden  22  2.6   97.4  20  ...  0.7  24  2.45  2       Agility
..                 ...  ..  ...    ...  ..  ...  ...  ..   ... ..           ...
118         Windranger  18    3    105  17  ...  0.8  24  2.05  2  Intelligence
119       WinterWyvern  24  2.6   99.4  16  ...  0.6  24  2.65  2  Intelligence
120        WitchDoctor  18  2.3   84.7  13  ...  0.6  24  2.05  2  Intelligence
121         WraithKing  22    3    109  18  ...  0.6  24  2.45  2      Strength
122               Zeus  19  2.1   79.9  11  ...  0.6  24  2.15  2  Intelligence

[122 rows x 29 columns]

In [25]:
#export the file
final.to_csv('dota2.csv', index = False)